# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-20 15:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photoblog', '0002_remove_user_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_confirm',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='uuid',
            field=models.CharField(default=True, max_length=200, null=True),
        ),
    ]
