# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-20 15:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photoblog', '0003_auto_20170420_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email_confirm',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active'),
        ),
    ]
