# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-20 15:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photoblog', '0004_auto_20170420_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
