# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-20 15:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('photoblog', '0005_auto_20170420_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.SlugField(default=uuid.UUID('e4204a4e-b9e1-4239-b970-389747193d70'), unique=True),
        ),
    ]
