# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-20 16:06
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('photoblog', '0007_auto_20170420_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.SlugField(blank=True, default=uuid.UUID('3e14fb5d-3718-4345-bd2d-1847bb401856'), null=True, unique=True),
        ),
    ]
